# Generated by Django 5.2.8 on 2025-11-22 10:47

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_remove_transaction_balance_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='salesitem',
            old_name='price',
            new_name='selling_price',
        ),
        migrations.RemoveField(
            model_name='sales',
            name='payment_method',
        ),
        migrations.RemoveField(
            model_name='sales',
            name='payment_status',
        ),
        migrations.RemoveField(
            model_name='sales',
            name='sale_type',
        ),
        migrations.RemoveField(
            model_name='sales',
            name='salesperson',
        ),
        migrations.RemoveField(
            model_name='sales',
            name='tax',
        ),
        migrations.RemoveField(
            model_name='sales',
            name='total_amount',
        ),
        migrations.RemoveField(
            model_name='salesitem',
            name='discount',
        ),
        migrations.AddField(
            model_name='sales',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='sales',
            name='grand_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='sales',
            name='paid_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='sales',
            name='status',
            field=models.CharField(choices=[('completed', 'Completed'), ('pending', 'Pending'), ('cancelled', 'Cancelled')], default='completed', max_length=20),
        ),
        migrations.AddField(
            model_name='sales',
            name='tax_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='salesitem',
            name='tax',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='sales',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.customer'),
        ),
        migrations.AlterField(
            model_name='sales',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='sales',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='salesitem',
            name='line_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='salesitem',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='app.product'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
