# Generated by Django 5.2.8 on 2025-11-22 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_rename_price_salesitem_selling_price_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sales',
            old_name='grand_total',
            new_name='total_amount',
        ),
        migrations.RenameField(
            model_name='salesitem',
            old_name='selling_price',
            new_name='price',
        ),
        migrations.RemoveField(
            model_name='sales',
            name='balance',
        ),
        migrations.RemoveField(
            model_name='sales',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='sales',
            name='paid_amount',
        ),
        migrations.RemoveField(
            model_name='sales',
            name='status',
        ),
        migrations.RemoveField(
            model_name='sales',
            name='tax_total',
        ),
        migrations.RemoveField(
            model_name='sales',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='salesitem',
            name='tax',
        ),
        migrations.AddField(
            model_name='sales',
            name='payment_status',
            field=models.CharField(choices=[('paid', 'Paid'), ('pending', 'Pending'), ('partial', 'Partial')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='sales',
            name='tax',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='salesitem',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
