# Generated by Django 5.2.8 on 2025-11-22 12:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_rename_grand_total_sales_total_amount_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sales',
            old_name='discount',
            new_name='grand_total',
        ),
        migrations.RenameField(
            model_name='sales',
            old_name='total_amount',
            new_name='total_tax',
        ),
        migrations.RemoveField(
            model_name='sales',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='sales',
            name='tax',
        ),
        migrations.RemoveField(
            model_name='salesitem',
            name='line_total',
        ),
        migrations.RemoveField(
            model_name='salesitem',
            name='quantity',
        ),
        migrations.AddField(
            model_name='sales',
            name='customer_name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='salesitem',
            name='qty',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='salesitem',
            name='tax',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='salesitem',
            name='total',
            field=models.DecimalField(decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='sales',
            name='invoice_no',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='sales',
            name='payment_status',
            field=models.CharField(choices=[('PAID', 'Paid'), ('PENDING', 'Pending'), ('CREDIT', 'Credit')], default='PENDING', max_length=10),
        ),
        migrations.AlterField(
            model_name='salesitem',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='salesitem',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='salesitem',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.product'),
        ),
    ]
