# Generated by Django 5.2.8 on 2025-11-23 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_salesitem_discount_alter_salesitem_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sales',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
