# Generated by Django 5.2.8 on 2025-11-23 05:45

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_alter_sales_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item.qty',
            name='amount_paid',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='discount',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='grand_total',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='payment_status',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='payment_type',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='remarks',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='subtotal',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='supplier',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='tax',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='transaction_no',
        ),
        migrations.RemoveField(
            model_name='transactionitem',
            name='price',
        ),
        migrations.RemoveField(
            model_name='transactionitem',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='transactionitem',
            name='total',
        ),
        migrations.AddField(
            model_name='transaction',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='transaction',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='reference',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='transactionitem',
            name='description',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='transactionitem',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Absolute discount per line', max_digits=12),
        ),
        migrations.AddField(
            model_name='transactionitem',
            name='qty',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=12),
        ),
        migrations.AddField(
            model_name='transactionitem',
            name='tax',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Absolute tax per line', max_digits=12),
        ),
        migrations.AddField(
            model_name='transactionitem',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='date',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('SALE', 'Sale'), ('PURCHASE', 'Purchase'), ('PAYMENT', 'Payment'), ('RECEIPT', 'Receipt'), ('STOCK_MOVE', 'Stock Move')], max_length=20),
        ),
        migrations.AlterField(
            model_name='transactionitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.product'),
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('code', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.account')),
            ],
        ),
        migrations.AddField(
            model_name='transaction',
            name='account',
            field=models.ForeignKey(blank=True, help_text='Primary account (customer/supplier/cash)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.account'),
        ),
        migrations.CreateModel(
            name='LedgerEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('debit', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('credit', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.account')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ledger_entries', to='app.transaction')),
            ],
        ),
    ]
