# Generated by Django 5.2.8 on 2025-11-23 17:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_journal_remove_transactionitem_product_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transactionline',
            name='account',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='journal',
        ),
        migrations.RemoveField(
            model_name='transactionline',
            name='transaction',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='narration',
            new_name='notes',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='reference',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='transaction',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='sale',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='app.sales'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('SALE', 'Sale'), ('PAYMENT', 'Payment'), ('REFUND', 'Refund')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.DeleteModel(
            name='Account',
        ),
        migrations.DeleteModel(
            name='Journal',
        ),
        migrations.DeleteModel(
            name='TransactionLine',
        ),
    ]
